{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insertapi.serviceAccountName" . }}
  labels:
{{ include "insertapi.labels" . | nindent 4 }}
{{- end -}}