{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "getapi.serviceAccountName" . }}
  labels:
{{ include "getapi.labels" . | nindent 4 }}
{{- end -}}